services:
  - type: web
    name: blueprint-detector
    env: python
    buildCommand: apt-get update && apt-get install -y poppler-utils && pip install -r backend/requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: API_BASE_URL
        value: https://blueprint-detector.onrender.com
      - key: PORT
        value: 10000
    buildFilter:
      paths:
        - backend/**
